(function($){Drupal.behaviors.captcha={attach:function(context){$("#edit-captcha-response").attr("autocomplete","off");}};Drupal.behaviors.captchaAdmin={attach:function(context){$("#edit-captcha-add-captcha-description").click(function(){if($("#edit-captcha-add-captcha-description").is(":checked")){$("div.form-item-captcha-description").show('slow');}
else{$("div.form-item-captcha-description").hide('slow');}});if(!$("#edit-captcha-add-captcha-description").is(":checked")){$("div.form-item-captcha-description").hide();}}};})(jQuery);;;(function($){function sanitizeHTML(str){return $("<div>").html(str).text();}
function escapeHtml(text){return text.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");}
function escapeRegExp(str){str=$.trim(str);return str.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g,"\\$&");}
$.ui.autocomplete.prototype._renderItem=function(ul,item){var term=escapeHtml(this.term);var first=("group"in item)?'first':'';var innerHTML='<div class="ui-autocomplete-fields '+first+'">';item.value=sanitizeHTML(item.value);item.label=sanitizeHTML(item.label);if(item.fields){$.each(item.fields,function(key,value){var regex=new RegExp('('+escapeRegExp(term)+')','gi');var output=sanitizeHTML(value);if(value.indexOf('src=')==-1&&value.indexOf('href=')==-1){output=output.replace(regex,"<span class='ui-autocomplete-field-term'>$1</span>");innerHTML+=('<div class="ui-autocomplete-field-'+key+'">'+output+'</div>');}else{innerHTML+=('<div class="ui-autocomplete-field-'+key+'">'+value+'</div>');}});}else{innerHTML+=('<div class="ui-autocomplete-field">'+item.label+'</div>');}
innerHTML+='</div>';var group='';if("group"in item){groupId=typeof(item.group.group_id)!=='undefined'?item.group.group_id:'';groupName=typeof(item.group.group_name)!=='undefined'?item.group.group_name:'';group+=('<div class="ui-autocomplete-field-group '+groupId+'">'+groupName+'</div>');$(group).appendTo(ul);}
var elem=$("<li class=ui-menu-item-"+first+"></li>").append("<a>"+innerHTML+"</a>");if(item.value==''){elem=$("<li class='ui-state-disabled ui-menu-item-"+first+" ui-menu-item'>"+item.label+"</li>");}
elem.data("item.autocomplete",item).appendTo(ul);Drupal.attachBehaviors(elem);return elem;};$.ui.autocomplete.prototype._resizeMenu=function(){var ul=this.menu.element;ul.outerWidth(Math.max(ul.width("").outerWidth()+5,this.options.position.of==null?this.element.outerWidth():this.options.position.of.outerWidth()));};Drupal.behaviors.search_autocomplete={attach:function(context){if(Drupal.settings.search_autocomplete){$.each(Drupal.settings.search_autocomplete,function(key,value){$(Drupal.settings.search_autocomplete[key].selector).bind("mouseover",function(){$(Drupal.settings.search_autocomplete[key].selector).addClass('form-autocomplete ui-autocomplete-processed').attr('data-sa-theme',Drupal.settings.search_autocomplete[key].theme).autocomplete({minLength:Drupal.settings.search_autocomplete[key].minChars,source:function(request,response){$(Drupal.settings.search_autocomplete[key].selector).addClass('throbbing');if(Drupal.settings.search_autocomplete[key].type=='external'){$.getJSON(Drupal.settings.search_autocomplete[key].datas,{q:encodeURIComponent(request.term)},function(results){if(results.length){results.slice(0,Drupal.settings.search_autocomplete[key].max_sug);}
response(results);});}
else if(Drupal.settings.search_autocomplete[key].type=='internal'||Drupal.settings.search_autocomplete[key].type=='view'){$.getJSON('https://proroid.is/search_autocomplete/autocomplete/3/',request,function(results){if(results.length){results.slice(0,Drupal.settings.search_autocomplete[key].max_sug);}
response(results);});}
else if(Drupal.settings.search_autocomplete[key].type=='static'){var results=$.ui.autocomplete.filter(Drupal.settings.search_autocomplete[key].datas,request.term);if(results.length){results.slice(0,Drupal.settings.search_autocomplete[key].max_sug);}
response(results);}},open:function(event,ui){$(".ui-autocomplete li.ui-menu-item:odd").addClass("ui-menu-item-odd");$(".ui-autocomplete li.ui-menu-item:even").addClass("ui-menu-item-even");$(Drupal.settings.search_autocomplete[key].selector).removeClass('throbbing');},select:function(event,ui){if(Drupal.settings.search_autocomplete[key].auto_redirect==1&&ui.item.link){document.location.href=ui.item.link;}else if(Drupal.settings.search_autocomplete[key].auto_submit==1&&ui.item.value){$(this).val(ui.item.value);$(this).closest("form").submit();}
$(this).val(sanitizeHTML(ui.item.value));},focus:function(event,ui){if(typeof ui.item.group!='undefined'){if(ui.item.group.group_id=='no_results'||ui.item.group.group_id=='all_results'){event.preventDefault();}}},appendTo:$(Drupal.settings.search_autocomplete[key].selector).parent()}).autocomplete("widget").attr("data-sa-theme",Drupal.settings.search_autocomplete[key].theme);});$(Drupal.settings.search_autocomplete[key].selector).trigger('mouseover');});}}};})(jQuery);;(function($){Drupal.googleanalytics={};$(document).ready(function(){$(document.body).bind("mousedown keyup touchstart",function(event){$(event.target).closest("a,area").each(function(){if(Drupal.googleanalytics.isInternal(this.href)){if($(this).is('.colorbox')&&(Drupal.settings.googleanalytics.trackColorbox)){}
else if(Drupal.settings.googleanalytics.trackDownload&&Drupal.googleanalytics.isDownload(this.href)){ga("send",{"hitType":"event","eventCategory":"Downloads","eventAction":Drupal.googleanalytics.getDownloadExtension(this.href).toUpperCase(),"eventLabel":Drupal.googleanalytics.getPageUrl(this.href),"transport":"beacon"});}
else if(Drupal.googleanalytics.isInternalSpecial(this.href)){ga("send",{"hitType":"pageview","page":Drupal.googleanalytics.getPageUrl(this.href),"transport":"beacon"});}}
else{if(Drupal.settings.googleanalytics.trackMailto&&$(this).is("a[href^='mailto:'],area[href^='mailto:']")){ga("send",{"hitType":"event","eventCategory":"Mails","eventAction":"Click","eventLabel":this.href.substring(7),"transport":"beacon"});}
else if(Drupal.settings.googleanalytics.trackOutbound&&this.href.match(/^\w+:\/\//i)){if(Drupal.settings.googleanalytics.trackDomainMode!==2||(Drupal.settings.googleanalytics.trackDomainMode===2&&!Drupal.googleanalytics.isCrossDomain(this.hostname,Drupal.settings.googleanalytics.trackCrossDomains))){ga("send",{"hitType":"event","eventCategory":"Outbound links","eventAction":"Click","eventLabel":this.href,"transport":"beacon"});}}}});});if(Drupal.settings.googleanalytics.trackUrlFragments){window.onhashchange=function(){ga("send",{"hitType":"pageview","page":location.pathname+location.search+location.hash});};}
if(Drupal.settings.googleanalytics.trackColorbox){$(document).bind("cbox_complete",function(){var href=$.colorbox.element().attr("href");if(href){ga("send",{"hitType":"pageview","page":Drupal.googleanalytics.getPageUrl(href)});}});}});Drupal.googleanalytics.isCrossDomain=function(hostname,crossDomains){if(!crossDomains){return false;}
else{return $.inArray(hostname,crossDomains)>-1?true:false;}};Drupal.googleanalytics.isDownload=function(url){var isDownload=new RegExp("\\.("+Drupal.settings.googleanalytics.trackDownloadExtensions+")([\?#].*)?$","i");return isDownload.test(url);};Drupal.googleanalytics.isInternal=function(url){var isInternal=new RegExp("^(https?):\/\/"+window.location.host,"i");return isInternal.test(url);};Drupal.googleanalytics.isInternalSpecial=function(url){var isInternalSpecial=new RegExp("(\/go\/.*)$","i");return isInternalSpecial.test(url);};Drupal.googleanalytics.getPageUrl=function(url){var extractInternalUrl=new RegExp("^(https?):\/\/"+window.location.host,"i");return url.replace(extractInternalUrl,'');};Drupal.googleanalytics.getDownloadExtension=function(url){var extractDownloadextension=new RegExp("\\.("+Drupal.settings.googleanalytics.trackDownloadExtensions+")([\?#].*)?$","i");var extension=extractDownloadextension.exec(url);return(extension===null)?'':extension[1];};})(jQuery);;;